version: '3'
services:
  mariadb:
    container_name: mariadb
    image: fabiojanio/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      #- CHARACTER_SET_SERVER=utf8
      #- COLLATION_SERVER=utf8_unicode_ci
      #- MYSQL_PORT=3306
      #- MYSQL_DATABASE= 
      #- MYSQL_USER=
      #- MYSQL_PASSWORD=
    volumes:
      - ./mysql/tmp:/var/lib/mysql
    restart: on-failure
    ports:
      - 3306:3306

  web:
    container_name: web
    image: fabiojanio/php-apache:7.2-stretch
    environment:
      # PODE ser prod ou dev, por default assume prod
      - TIPO_AMBIENTE=prod
    volumes:
      - ./projeto:/var/www
      #- ./apache:/etc/apache2/sites-enabled/
    working_dir: /var/www
    depends_on:
      - mariadb
    links:
      - mariadb
    restart: on-failure
    ports:
      - 80:80